#!/bin/bash

echo "The lines prefixed with '-' are wrong output lines present in your output and not present in the expected output. 
The lines prefixed with '+' are present in the expected output and should be present in your output." 
while read -r line
do
  first_word=$(echo $line |awk '{print $1 $2}')
  #echo "$first_word"
  first_character_=${first_word:0:1}
  if [ "$first_character_" != "@" ]
  then
      if [ "$first_character_" = "-"  ] && [ "${first_word:0:3}" = "---" ]
      then
          student_output_file=${line:3:-37}
          # echo "Your output file: $student_output_file"
      elif [ "$first_character_" = "+"  ] && [ "${first_word:0:3}" = "+++" ]
      then
          expected_output_file=${line:3:-37}
          # echo "Expected output file: $expected_output_file" 
          echo "$(basename ${expected_output_file%^}):"
      else
          echo $line 
      fi 
  fi
done < $1 
